# FROM nginx:1.27.0-alpine

# COPY ./default.conf /etc/nginx/conf.d/default.conf

FROM nginx:1.27.0-alpine

COPY ./default.conf /etc/nginx/conf.d/default.conf
# COPY ./frontend/build /var/www/frontend

# Optional: ensure /static directory exists and has the necessary files
# RUN mkdir -p /static

EXPOSE 80